[package]
name = "rank"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed", features = ["wayland"] }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["font-kit", "wayland"] }
gpui-component = { git = "https://github.com/longbridge/gpui-component" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component" }
seq-macro = "0.3.6"
rand = "0.10.1"

[profile.release]
debug = "limited"
lto = "thin"
codegen-units = 1

[profile.release.package]
rank = { codegen-units = 16 }
