name: Release

on:
    push:
        tags:
            - v[0-9]+.*

permissions:
    contents: write

jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v6.0.2
            - uses: taiki-e/create-gh-release-action@v1
              with:
                  # (optional) Path to changelog.
                  changelog: CHANGELOG.md
              env:
                  # (required) GitHub token for creating GitHub Releases.
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    upload-assets:
        needs: create-release
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - target: x86_64-unknown-linux-gnu
                      os: ubuntu-latest
                    - target: aarch64-apple-darwin
                      os: macos-latest
                    - target: x86_64-pc-windows-msvc
                      os: windows-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v6.0.2
            - name: Install dependencies
              run: script/bootstrap
            - uses: taiki-e/upload-rust-binary-action@v1
              with:
                  # (required) Binary name (non-extension portion of filename) to build and upload.
                  bin: rank
                  target: ${{ matrix.target }}
                  # (optional) Whether to create the leading directory in the archive or not. default to false.
                  leading-dir: true
                  # (optional) Comma-separated list of additional files to be included to archive.
                  # Note that glob pattern is not supported yet.
                  # include: LICENSE, README.md
              env:
                  # (required) GitHub token for uploading assets to GitHub Releases.
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
